config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :label
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  enum status: {"未着手":0, "着手中":1, "完了":2}
  enum priority_level: {"高":0, "中":1, "低":2}
  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  scope :title_search, -> (title) {where('title LIKE ?',"%#{title}%") }
  scope :status_search, -> (status) {where(status: status)}
  scope :label_search, -> (label) {where(id: Labeling.where(label_id: label).select(:task_id))}
  # scope :title_search, -> (params) { where('(title Like ?)',"%#{params[:task][:title]}%") }
  # scope :status_search, -> (params) {where(status: params[:task][:status])}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  validates :password, length: { minimum: 6 }
  has_secure_password
  has_many :tasks, dependent: :destroy
  before_destroy :last_one_admin
  before_update :last_one_admin

  private

  def last_one_admin
    if User.find(id).admin
      throw(:abord) if (User.where(admin:true).count - [self].count == 0)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create ]
  before_action :if_not_admin

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザーを作成しました！"
    else
      render :new
    end
  end

  def show
     @user = User.find(params[:id])
  end

  def index
    @users = User.all
    # @users = User.select(:name, :email, :id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'ユーザーを編集しました！'
      redirect_to  admin_users_path
    else
      flash[:notice] = '変更内容に誤りがあるか、管理者ユーザーがいなくなるため削除できません'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = '削除しました'
      redirect_to admin_users_path
    else
      flash[:notice] = '削除できません'
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:admin, :name, :email, 
    :password, :password_confirmation)
  end

  def login_already
    if current_user
      flash[:notice]="ログイン中です"
      redirect_to user_path(current_user.id)
    end
  end

  def user_check
    if current_user.id != params[:id].to_i
      flash[:notice]="アクセス権限がありません"
      redirect_to user_path(current_user.id)
    end
  end

  def if_not_admin
    redirect_to tasks_path, notice: "管理者権限がありません。" unless admin_user?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create ]
  
  def new

  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.all.includes(:user).order(due: :desc).page(params[:page]).per(5)

      # @tasks = Task.all.order(due: :desc).page(params[:page]).per(5)
    elsif params[:priority_level]
      @tasks = current_user.tasks.all.includes(:user).order(priority_level: :asc).page(params[:page]).per(5)
      # @tasks = Task.all.order(priority_level: :asc).page(params[:page]).per(5)
    else
      @tasks = current_user.tasks.all.includes(:user).order(created_at: :desc).page(params[:page]).per(5)

      # @tasks = Task.all.order(created_at: :desc).page(params[:page]).per(5)
    end

    if params[:task].present?
      task_status = params[:task][:status]
      task_title = params[:task][:title]
      task_label = params[:task][:label_ids]
      if task_status.present? && task_title.present? 
        @tasks = current_user.tasks.title_search(task_title).page(params[:page]).per(5)
        @tasks = current_user.tasks.status_search(task_status).page(params[:page]).per(5)
      elsif task_title.present?
        @tasks = current_user.tasks.title_search(task_title).page(params[:page]).per(5)
        # @tasks = Task.title_search(params[:task][:title]).page(params[:page]).per(5)
      elsif task_status.present? 
        @tasks = current_user.tasks.status_search(task_status).page(params[:page]).per(5)
      elsif task_label.present?
        @tasks = current_user.tasks.label_search(task_label).page(params[:page]).per(5)

      end
    end   
  end

  def new
    @task = Task.new
  end


  def create
    @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:notice] = 'タスク作成しました！'
      redirect_to tasks_path
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    labels = Labeling.where(task_id: @task.id).pluck(:label_id)
    @labels = Label.find(labels)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = '編集しました！'
      redirect_to tasks_path
    else 
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      flash[:notice] = '削除しました！'
      redirect_to tasks_path
    end
  end

  private

  def task_params
    params.require(:task).permit(:content, :title, :due, :status, :priority_level, {label_ids: []})
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :login_already, only: [:new]
  before_action :user_check, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:admin, :name, :email, :password, :password_confirmation)
  end

  def login_already
    if current_user
      flash[:notice]="ログイン中です"
      redirect_to user_path(current_user.id)
    end
  end

  def user_check
    if current_user.id != params[:id].to_i
      flash[:notice]="アクセス権限がありません"
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
      
  def logged_in?
      current_user.present?
  end

  def admin_user?
    current_user.admin == true
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザー編集画面</h1>
<%= form_with(model: @user, url: admin_user_path(@user.id), local: true) do |f| %> 

  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label '管理者権限' %>
    <%= f.select :admin, [["一般ユーザー","false"], ["管理者ユーザー","true"]]  %>
  
    <%= f.label :password %>
    <%= f.password_field :password %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  
    <%= f.submit "登録する" %>
  <% end %>

app/views/admin/users/index.html.erb
<h1>ユーザー 一覧画面(管理者)</h1>
<body>
<table class="table table-striped table-bordered">
<head>
<th>名前</th>
<th>メールアドレス</th>
<th>投稿数</th>
</head>
<% @users.each do |t| %>
  <tr class="user_row" >
  <td><%= t.name %></td>
  <td><%= t.email %></td>
  <td><%= t.tasks.count %></td>
  <td><%= link_to '投稿', admin_user_path(t) %></td>
  <td><%= link_to '編集', edit_admin_user_path(t) %></td>
  <td><%= link_to '削除', admin_user_path(t), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'ユーザー追加', new_admin_user_path%>
</body>

app/views/admin/users/new.html.erb
<h1>ユーザー登録画面</h1>

<%= form_with(model: @user, url: admin_users_path, local: true) do |f| %> 

<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

  <%= f.label '名前' %>
  <%= f.text_field :name %>

  <%= f.label 'Eメール' %>
  <%= f.email_field :email %>

  <%= f.label '管理者権限' %>
  <%= f.select :admin, [["一般ユーザー","false"], ["管理者ユーザー","true"]]  %>
  
  <%= f.label 'パスワード' %>
  <%= f.password_field :password %>

  <%= f.label '確認パスワード' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "登録する" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>の投稿タスク</h1>
<body>
<table class="table table-striped table-bordered">

<head>
<th>タスク名</th>
<th>タスク詳細</th>
<th>投稿日</th>
<th>終了期限</th>
<th>優先度</th>
<th>ステータス</th>
</head>

<% @user.tasks.each do |t| %>
<tr class="task_row" >
<td><%= t.title %></td>
<td><%= t.content %></td>
<td><%= t.created_at.strftime("%Y-%m-%d %H:%M")  %></td>
<td><%= t.due.strftime("%Y-%m-%d")  %></td>
<td><%= t.priority_level  %></td>
<td><%= t.status  %></td>
</tr>
<% end %>

</table>
</body>
<%= link_to 'ユーザー 一覧', admin_users_path %>
<br>
<%= link_to 'タスク 一覧', tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DicManyo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to 'profile', user_path(current_user.id) %>
      <%= link_to 'Logout', session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to 'Sign up', new_user_path %>
      <%= link_to 'Login', new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<br>
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, t('.errors')) %></h2>
        <% task.errors.full_messages.each do |error| %>
          <%= error %>
          <br>
        <% end %>
    </div>
  <% end %>

  <div>
    <%= f.label 'title' %>
    <br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label 'content' %>
    <br>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.label t('.due_date') %>
    <br>
    <%= f.datetime_select :due %>
  </div>
  <div>
    <%= f.label t('.status') %>
    <br>
    <%= f.select :status, Task.statuses.keys %>
  </div>
  <div>
    <%= f.label '優先度' %>
    <br>
    <%= f.select :priority_level, Task.priority_levels.keys %>
  </div>
  <div>
    <%= f.label 'ラベル' %>
    <br>
    <label>
    <% Label.all.each do |label|%>
      <%= f.check_box :label_ids, { multiple: true, checked: @task.labels.find_by(id: label.id).present?, include_hidden: false}, label[:id] %>
      <%= label.label_name %>
    <% end %>
    </label>
  </div>
  <br>

  <% if current_page?(new_task_path) %>
    <%= f.submit %>
  <% else %>
    <%= f.submit t('.update') %>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= t('.head') %> </h1>
<%= render 'form', task: @task %>
<%= link_to t('.content'), @task %> 
<%= link_to t('.list'), tasks_path %>

app/views/tasks/index.html.erb
<h1><%= t('.head') %></h1>
<body>
  <%= form_with( model:Task.new, local: true, method: :get, url: tasks_path) do |f| %>
    <table>
    <th><%= t('.title') %><%= f.text_field :title %></th>
    <th><%= t('.status') %><%= f.select  :status, [["", ""], ["未着手", 0], ["着手中", 1], ["完了", 2]] %></th>
    </table>
    <div>ラベル: <%= f.select("label_ids", Label.pluck(:label_name, :id), { include_blank: true }) %></div>
    <%= f.submit '検索', class: 'btn btn-primary' %>
    <% end %>
  </div>



  <p>
    <%= link_to t('.sort by created at'), tasks_path %>
  </p>

  <table class="table table-striped table-bordered">
    <head>
      <th><%= t('.user_name') %></th>
      <th><%= t('.create_date') %></th>
      <th><%= link_to t('.sort by due date'), tasks_path(sort_expired: "true") %></th>
      <th><%= t('.status') %></th>
      <th><%= link_to t('.sort by priority'), tasks_path(priority_level: "true") %></th>
      <th><%= t('.title') %></th>
      <th><%= t('.content') %></th>
    </head>

    <% @tasks.each do |t| %>
      <tr class="task_row" >
      <td><%= t.user.name %></td>
      <td><%= t.created_at.strftime("%Y-%m-%d %H:%M") %></td>
      <td><%= t.due.strftime("%Y-%m-%d") %></td>
      <td><%= t.status %></td>
      <td><%= t.priority_level %></td>
      <td><%= t.title %></td>
      <td><%= t.content %></td>
      <td><%= link_to t('.show'), t %></td>
      <td><%= link_to t('.edit'), edit_task_path(t) %></td>
      <td><%= link_to t('.destroy'), t, method: :delete, data: { confirm: t('.confirm') } %></td>
      </tr>
    <% end %>

    
    </table>
</body>

<%= link_to t('.new'), new_task_path %>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<br>
<h2><%= t('.new_form') %></h2>
<%= render 'form', task: @task %>
<%= link_to t('.list'), tasks_path %>

app/views/tasks/show.html.erb
<div class="text-center">
<h1>タスクの詳細</h1>  
  <b><%= t('.create_date') %></b>
  <%= @task.created_at.strftime("%Y-%m-%d %H:%M") %>
  <br>
  <b><%= t('.title') %></b>
  <%= @task.title %>
  <br>
  <b><%= t('.content') %></b>
  <%= @task.content %>
  <br>
  <b><%= t('.due_date') %></b>
  <%= @task.due.strftime("%Y-%m-%d") %>
  <br>
  <b><%= t('.status') %></b>
  <%= @task.status %>
  <p><b>ラベル</b>:
  <% @labels.each do |tag| %>
    <%= tag.label_name %>
  <% end %>
  </p>
</div>
  <br>
<%= link_to t('.list'), tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %> 

<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "登録する" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>


<%= link_to 'タスク一覧', tasks_path %>

<% if @user.admin? %>
<%= link_to 'ユーザー一覧', admin_users_path%>
<% end %>